
CREATE TABLE FOURNISSEUR (
  ID_FOUR NUMBER PRIMARY KEY,
  NOM VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(120),
  TEL VARCHAR2(30)
);
CREATE TABLE MATIERE_PREMIERE (
  ID_MP NUMBER PRIMARY KEY,
  REFERENCE VARCHAR2(50) UNIQUE NOT NULL,
  NOM VARCHAR2(120) NOT NULL,
  QUANTITE NUMBER DEFAULT 0 CHECK (QUANTITE >= 0),
  SEUIL_CRITIQUE NUMBER DEFAULT 0 CHECK (SEUIL_CRITIQUE >= 0),
  PRIX NUMBER(12,3) DEFAULT 0 CHECK (PRIX >= 0),
  DATE_FABRICATION DATE,
  DATE_ACHAT DATE,
  ID_FOUR NUMBER,
  CONSTRAINT FK_MP_FOUR FOREIGN KEY (ID_FOUR) REFERENCES FOURNISSEUR(ID_FOUR)
);
CREATE TABLE CLIENT (
  ID_CLIENT NUMBER PRIMARY KEY,
  NOM VARCHAR2(120) NOT NULL,
  MATRICULE VARCHAR2(50) UNIQUE,
  EMAIL VARCHAR2(120),
  TYPE_CONTRAT VARCHAR2(50),
  STATUT_PAIEMENT VARCHAR2(20)
    CHECK (STATUT_PAIEMENT IN ('A_JOUR','EN_RETARD','SUSPENDU'))
);
CREATE TABLE BAC_INTEL (
  ID_BAC NUMBER PRIMARY KEY,
  NUM_SERIE VARCHAR2(60) UNIQUE NOT NULL,
  MODELE VARCHAR2(60) NOT NULL,
  REMPLISSAGE NUMBER DEFAULT 0 CHECK (REMPLISSAGE BETWEEN 0 AND 100),
  LOCALISATION_STOCK VARCHAR2(150),
  ID_CLIENT NUMBER NULL,
  CONSTRAINT FK_BAC_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);
CREATE TABLE EMPLOYE (
  ID_EMP NUMBER PRIMARY KEY,
  MATRICULE VARCHAR2(30) UNIQUE NOT NULL,
  CIN VARCHAR2(20) UNIQUE,
  NOM VARCHAR2(80) NOT NULL,
  EMAIL VARCHAR2(120) UNIQUE,
  SPECIALITE VARCHAR2(80),
  DISPONIBILITE VARCHAR2(20) DEFAULT 'DISPONIBLE'
    CHECK (DISPONIBILITE IN ('DISPONIBLE','INDISPONIBLE'))
);
CREATE TABLE COMMANDE (
  ID_COMMANDE NUMBER PRIMARY KEY,
  ID_CLIENT NUMBER NOT NULL,
  QTE NUMBER NOT NULL CHECK (QTE > 0),
  PRIORITE VARCHAR2(15) DEFAULT 'NORMALE'
    CHECK (PRIORITE IN ('FAIBLE','NORMALE','HAUTE','URGENTE')),
  STATUT VARCHAR2(20) DEFAULT 'EN_PREPARATION'
    CHECK (STATUT IN ('EN_PREPARATION','LIVREE','INSTALLEE','ANNULEE')),
  DATE_COMMANDE DATE DEFAULT SYSDATE,
  DATE_LIVRAISON DATE,
  PRIX_TOTAL NUMBER(12,3) DEFAULT 0 CHECK (PRIX_TOTAL >= 0),
  CONSTRAINT FK_CMD_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);
CREATE TABLE INTERVENTION (
  ID_INTER NUMBER PRIMARY KEY,
  ID_BAC NUMBER NOT NULL,
  ID_EMP NUMBER NOT NULL,
  DATE_INTER DATE DEFAULT SYSDATE,
  REFERENCE VARCHAR2(60),
  DUREE NUMBER(6,2) DEFAULT 0 CHECK (DUREE >= 0),
  COUT NUMBER(12,3) DEFAULT 0 CHECK (COUT >= 0),
  STATUT VARCHAR2(20) DEFAULT 'EN_COURS'
    CHECK (STATUT IN ('EN_COURS','TERMINEE','ANNULEE')),
  TYPE VARCHAR2(60),
  PRIORITE VARCHAR2(15) DEFAULT 'NORMALE'
    CHECK (PRIORITE IN ('FAIBLE','NORMALE','HAUTE','URGENTE')),
  CONSTRAINT FK_INTER_BAC FOREIGN KEY (ID_BAC) REFERENCES BAC_INTEL(ID_BAC),
  CONSTRAINT FK_INTER_EMP FOREIGN KEY (ID_EMP) REFERENCES EMPLOYE(ID_EMP)
);
CREATE TABLE INTERVENTION_MATIERE (
  ID_INTER NUMBER NOT NULL,
  ID_MP NUMBER NOT NULL,
  QTE_UTILISEE NUMBER NOT NULL CHECK (QTE_UTILISEE > 0),
  PRIMARY KEY (ID_INTER, ID_MP),
  CONSTRAINT FK_IM_INTER FOREIGN KEY (ID_INTER) REFERENCES INTERVENTION(ID_INTER),
  CONSTRAINT FK_IM_MP FOREIGN KEY (ID_MP) REFERENCES MATIERE_PREMIERE(ID_MP)
);