--------------------------------------------------------
--  File created - Thursday-April-16-2026   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence BAC_INTEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."BAC_INTEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAC_INTEL_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."BAC_INTEL_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAC_INTEL_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."BAC_INTEL_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAC_INTEL_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."BAC_INTEL_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."CLIENT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMANDE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."COMMANDE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMANDE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."COMMANDE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."EMPLOYE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."EMPLOYE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURNISSEUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."FOURNISSEUR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INTERVENTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."INTERVENTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INTERVENTION_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."INTERVENTION_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MATIERE_PREMIERE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."MATIERE_PREMIERE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MATIERE_PREMIERE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."MATIERE_PREMIERE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CMD_REF
--------------------------------------------------------

   CREATE SEQUENCE  "WASTEGUARD"."SEQ_CMD_REF"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table BAC_INTEL
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."BAC_INTEL" 
   (	"ID_BAC" NUMBER, 
	"NUM_SERIE" VARCHAR2(60 BYTE), 
	"MODELE" VARCHAR2(60 BYTE), 
	"REMPLISSAGE" NUMBER DEFAULT 0, 
	"LOCALISATION_STOCK" VARCHAR2(150 BYTE), 
	"ID_COMMANDE" NUMBER, 
	"PRIX" NUMBER(12,3), 
	"STOCK" NUMBER, 
	"CAPACITE_BATTERIE" NUMBER(8,2), 
	"CARACTERISTIQUES" VARCHAR2(500 BYTE), 
	"IMAGE_PATH" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(120 BYTE), 
	"MATRICULE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(120 BYTE), 
	"TYPE_CONTRAT" VARCHAR2(50 BYTE), 
	"STATUT_PAIEMENT" VARCHAR2(20 BYTE), 
	"DATE_EXPIRATION_CONTRAT" DATE, 
	"TAUX_TRI" NUMBER DEFAULT 0, 
	"TELEPHONE" VARCHAR2(30 BYTE), 
	"DATE_CREATION_CONTRAT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"ID_CLIENT" NUMBER, 
	"QTE" NUMBER, 
	"PRIORITE" VARCHAR2(16 BYTE) DEFAULT 'NORMALE', 
	"STATUT" VARCHAR2(21 BYTE) DEFAULT 'EN_PREPARATION', 
	"DATE_COMMANDE" DATE DEFAULT SYSDATE, 
	"DATE_LIVRAISON" DATE, 
	"PRIX_TOTAL" NUMBER(12,3) DEFAULT 0, 
	"ADRESSE" VARCHAR2(300 BYTE), 
	"REFER" VARCHAR2(9 BYTE), 
	"START_ADRESSE" VARCHAR2(100 BYTE), 
	"PATH_HISTORY" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE_BAC
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."COMMANDE_BAC" 
   (	"ID_COMMANDE" NUMBER, 
	"ID_BAC" NUMBER, 
	"QTE" NUMBER, 
	"PRIX_UNITAIRE" NUMBER(12,3) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EFFECTUATION
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."EFFECTUATION" 
   (	"ID_EMP" NUMBER, 
	"ID_INTER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."EMPLOYE" 
   (	"ID_EMP" NUMBER, 
	"MATRICULE" VARCHAR2(30 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(120 BYTE), 
	"SPECIALITE" VARCHAR2(80 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE) DEFAULT 'DISPONIBLE', 
	"PHOTO" BLOB, 
	"FACE_TEMPLATE" CLOB, 
	"FACE_TEMPLATE_UPDATED_AT" DATE, 
	"FACE_ENABLED" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FACE_TEMPLATE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FABRICATION
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."FABRICATION" 
   (	"ID_MP" NUMBER, 
	"ID_BAC" NUMBER, 
	"QTE_UTILISE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INTERVENTION
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."INTERVENTION" 
   (	"ID_INTER" NUMBER, 
	"ID_BAC" NUMBER, 
	"DATE_INTER" DATE DEFAULT SYSDATE, 
	"REFERENCE" VARCHAR2(60 BYTE), 
	"DUREE" NUMBER(6,2) DEFAULT 0, 
	"COUT" NUMBER(12,3) DEFAULT 0, 
	"STATUT" VARCHAR2(20 BYTE) DEFAULT 'EN_COURS', 
	"TYPE" VARCHAR2(60 BYTE), 
	"PRIORITE" VARCHAR2(15 BYTE) DEFAULT 'NORMALE', 
	"TECHNICIEN" VARCHAR2(40 BYTE), 
	"DESCRIPT" VARCHAR2(255 BYTE), 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"PHOTO_AVANT" VARCHAR2(1000 BYTE), 
	"PHOTO_APRES" VARCHAR2(1000 BYTE), 
	"MAIN_OEUVRE" NUMBER(12,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATIERE_PREMIERE
--------------------------------------------------------

  CREATE TABLE "WASTEGUARD"."MATIERE_PREMIERE" 
   (	"ID_MP" NUMBER, 
	"REFERENCE" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(120 BYTE), 
	"QUANTITE" NUMBER DEFAULT 0, 
	"SEUIL_CRITIQUE" NUMBER DEFAULT 0, 
	"PRIX" NUMBER(12,3) DEFAULT 0, 
	"DATE_FABRICATION" DATE, 
	"DATE_ACHAT" DATE, 
	"NUM_FOUR" NUMBER, 
	"NOM_FOUR" VARCHAR2(50 BYTE), 
	"EMAIL_FOUR" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index PK_COMMANDE_BAC
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASTEGUARD"."PK_COMMANDE_BAC" ON "WASTEGUARD"."COMMANDE_BAC" ("ID_COMMANDE", "ID_BAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_COMMANDE_BAC_BAC
--------------------------------------------------------

  CREATE INDEX "WASTEGUARD"."IDX_COMMANDE_BAC_BAC" ON "WASTEGUARD"."COMMANDE_BAC" ("ID_BAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Trigger BAC_INTEL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."BAC_INTEL_TRG" 
BEFORE INSERT ON BAC_INTEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_BAC IS NULL THEN
      SELECT BAC_INTEL_SEQ3.NEXTVAL INTO :NEW.ID_BAC FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."BAC_INTEL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."CLIENT_TRG" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENT IS NULL THEN
      SELECT CLIENT_SEQ1.NEXTVAL INTO :NEW.ID_CLIENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."CLIENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMANDE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."COMMANDE_TRG" 
BEFORE INSERT ON COMMANDE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_COMMANDE IS NULL THEN
      SELECT COMMANDE_SEQ1.NEXTVAL INTO :NEW.ID_COMMANDE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."COMMANDE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."EMPLOYE_BI" 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
   WHEN (NEW.ID_EMP IS NULL) BEGIN
    SELECT EMPLOYE_SEQ.NEXTVAL INTO :NEW.ID_EMP FROM DUAL;
END;
/
ALTER TRIGGER "WASTEGUARD"."EMPLOYE_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."EMPLOYE_TRG" 
BEFORE INSERT ON EMPLOYE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMP IS NULL THEN
      SELECT EMPLOYE_SEQ1.NEXTVAL INTO :NEW.ID_EMP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."EMPLOYE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INTERVENTION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."INTERVENTION_TRG" 
BEFORE INSERT ON INTERVENTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_INTER IS NULL THEN
      SELECT INTERVENTION_SEQ1.NEXTVAL INTO :NEW.ID_INTER FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."INTERVENTION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATIERE_PREMIERE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."MATIERE_PREMIERE_TRG" 
BEFORE INSERT ON MATIERE_PREMIERE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MP IS NULL THEN
      SELECT MATIERE_PREMIERE_SEQ1.NEXTVAL INTO :NEW.ID_MP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASTEGUARD"."MATIERE_PREMIERE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CMD_REF
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASTEGUARD"."TRG_CMD_REF" 
BEFORE INSERT ON COMMANDE
FOR EACH ROW
BEGIN
    :NEW.REFER := 'CMD-' || LPAD(SEQ_CMD_REF.NEXTVAL, 3, '0');
END;
/
ALTER TRIGGER "WASTEGUARD"."TRG_CMD_REF" ENABLE;

--------------------------------------------------------
--  Constraints for Table FABRICATION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."FABRICATION" MODIFY ("ID_MP" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."FABRICATION" MODIFY ("ID_BAC" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."FABRICATION" MODIFY ("QTE_UTILISE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."FABRICATION" ADD PRIMARY KEY ("ID_MP", "ID_BAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."CLIENT" ADD CHECK (STATUT_PAIEMENT IN ('A_JOUR', 'EN_RETARD', 'SUSPENDU')) ENABLE;
  ALTER TABLE "WASTEGUARD"."CLIENT" ADD CHECK (TAUX_TRI BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "WASTEGUARD"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."CLIENT" ADD UNIQUE ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."EMPLOYE" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."EMPLOYE" ADD CHECK (DISPONIBILITE IN ('DISPONIBLE', 'INDISPONIBLE')) ENABLE;
  ALTER TABLE "WASTEGUARD"."EMPLOYE" ADD PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."EMPLOYE" ADD UNIQUE ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."EMPLOYE" ADD UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."EMPLOYE" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EFFECTUATION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."EFFECTUATION" MODIFY ("ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."EFFECTUATION" MODIFY ("ID_INTER" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."EFFECTUATION" ADD PRIMARY KEY ("ID_EMP", "ID_INTER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."COMMANDE" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE" MODIFY ("QTE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD CHECK (QTE > 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD CHECK (PRIORITE IN ('FAIBLE', 'NORMALE', 'HAUTE', 'URGENTE')) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD CHECK (STATUT IN ('EN_PREPARATION', 'LIVREE', 'INSTALLEE', 'ANNULEE')) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD CHECK (PRIX_TOTAL >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATIERE_PREMIERE
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" ADD CHECK (QUANTITE >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" ADD CHECK (SEUIL_CRITIQUE >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" ADD CHECK (PRIX >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" ADD PRIMARY KEY ("ID_MP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."MATIERE_PREMIERE" ADD UNIQUE ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVENTION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."INTERVENTION" MODIFY ("ID_BAC" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD CHECK (DUREE >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD CHECK (COUT >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD CHECK (PRIORITE IN ('FAIBLE', 'NORMALE', 'HAUTE', 'URGENTE')) ENABLE;
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD PRIMARY KEY ("ID_INTER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD UNIQUE ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD CONSTRAINT "SYS_C007359" CHECK (STATUT IN ('EN_COURS', 'EN_ATTENTE', 'TERMINEE', 'ANNULEE')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BAC_INTEL
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."BAC_INTEL" MODIFY ("NUM_SERIE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."BAC_INTEL" MODIFY ("MODELE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."BAC_INTEL" ADD CHECK (REMPLISSAGE BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "WASTEGUARD"."BAC_INTEL" ADD PRIMARY KEY ("ID_BAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASTEGUARD"."BAC_INTEL" ADD UNIQUE ("NUM_SERIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE_BAC
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" MODIFY ("ID_BAC" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" MODIFY ("QTE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" MODIFY ("PRIX_UNITAIRE" NOT NULL ENABLE);
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" ADD CONSTRAINT "CK_COMMANDE_BAC_QTE" CHECK (QTE > 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" ADD CONSTRAINT "CK_COMMANDE_BAC_PRIX" CHECK (PRIX_UNITAIRE >= 0) ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" ADD CONSTRAINT "PK_COMMANDE_BAC" PRIMARY KEY ("ID_COMMANDE", "ID_BAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."COMMANDE" ADD CONSTRAINT "FK_CMD_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "WASTEGUARD"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE_BAC
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" ADD CONSTRAINT "FK_COMMANDE_BAC_BAC" FOREIGN KEY ("ID_BAC")
	  REFERENCES "WASTEGUARD"."BAC_INTEL" ("ID_BAC") ENABLE;
  ALTER TABLE "WASTEGUARD"."COMMANDE_BAC" ADD CONSTRAINT "FK_COMMANDE_BAC_CMD" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "WASTEGUARD"."COMMANDE" ("ID_COMMANDE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EFFECTUATION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."EFFECTUATION" ADD CONSTRAINT "FK_EFFECTUATION_ID_INTER" FOREIGN KEY ("ID_INTER")
	  REFERENCES "WASTEGUARD"."INTERVENTION" ("ID_INTER") ENABLE NOVALIDATE;
  ALTER TABLE "WASTEGUARD"."EFFECTUATION" ADD FOREIGN KEY ("ID_EMP")
	  REFERENCES "WASTEGUARD"."EMPLOYE" ("ID_EMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FABRICATION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."FABRICATION" ADD CONSTRAINT "FK_FABRICATION_ID_MP" FOREIGN KEY ("ID_MP")
	  REFERENCES "WASTEGUARD"."MATIERE_PREMIERE" ("ID_MP") ENABLE NOVALIDATE;
  ALTER TABLE "WASTEGUARD"."FABRICATION" ADD FOREIGN KEY ("ID_BAC")
	  REFERENCES "WASTEGUARD"."BAC_INTEL" ("ID_BAC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVENTION
--------------------------------------------------------

  ALTER TABLE "WASTEGUARD"."INTERVENTION" ADD CONSTRAINT "FK_INTER_BAC" FOREIGN KEY ("ID_BAC")
	  REFERENCES "WASTEGUARD"."BAC_INTEL" ("ID_BAC") ENABLE;